on:
  push:
    branches:
    - fix
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use JDK-17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: build
      run: javac -d ./out/ -encoding utf-8 src/*.java
    - name: Package JAR
      run: jar cfe ./eComp.jar Greeting ./out/*.class
    - name: Run JAR
      run: java -jar ./eComp.jar 
